apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-gpu
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/vhive-serverless/hello-gpu:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              nvidia.com/gpu: 1
          env:
            - name: TARGET
              value: "GPU"