apiVersion: "power.intel.com/v1"
kind: PowerWorkload
metadata:
  name: performance-$NODE_NAME-workload
  namespace: intel-power
spec:
  name: "performance-$NODE_NAME-workload"
  allCores: true
  powerNodeSelector:
    # The label must be as below, as this workload will be specific to the Node
    kubernetes.io/hostname: $NODE_NAME
  # Replace this value with the intended shared PowerProfile
  powerProfile: "performance"