name: MinIO tests

on:
  # push:
  #   branches: [ main, legacy-firecracker-v0.24.0-with-upf-support ]
  #   paths-ignore:
  #   - 'docs/**'
  #   - '**.md'
  #   - 'function-images/**'
  # pull_request:
  #   branches: [ main, legacy-firecracker-v0.24.0-with-upf-support ]
  #   paths-ignore:
  #   - 'docs/**'
  #   - '**.md'
  #   - 'function-images/**'
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'

env:
  GOOS: linux
  GO111MODULE: on
  TMPDIR: /root/tmp/
  GOCACHE: /root/tmp/gocache
  GOPATH: /root/tmp/gopath
  KUBECONFIG: /etc/kubernetes/admin.conf

jobs:
  minio-test:
    name: Minio test
    runs-on: [stock-knative]

    steps:
    - name: Setup TMPDIR
      run: mkdir -p $TMPDIR

    - name: Set up Go 1.19
      uses: actions/setup-go@v5
      with:
        go-version: '1.19'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Build
      run: go build

    - name: modify $PATH
      run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

    - name: Setup minio
      run: sleep 1m && make -C ./function-images/tests/save_load_minio build_local

    - name: Test minio
      run: ./function-images/tests/save_load_minio/scripts/run_minio_k8s.sh

    - name: Archive log artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: ctrd-logs
        path: |
          /tmp/ctrd-logs/${{ github.run_id }}

    - name: Cleaning
      if: ${{ always() }}
      run: |
        make -C ./function-images/tests/save_load_minio clean
