name: vHive stock-only stargz tests

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
    - 'function-images/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - '**.md'
    - 'function-images/**'
  workflow_dispatch:

env:
  GOOS: linux
  GO111MODULE: on

jobs:
  stargz-container-test:
    name: Test running stargz-based image using kn
    env:
      KIND_VERSION: v0.14.0
      K8S_VERSION: v1.23
      YAML_DIR: workloads/container
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        service:
          [
            trace_func_go,
          ]

    steps:
    - name: Set up Go 1.18
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
    - name: Create k8s Kind Cluster
      run: bash ./scripts/stargz/01-kind.sh

    - name: Install Serving
      run: bash ./scripts/stargz/02-serving.sh

    - name: Install Kourier
      run: bash ./scripts/stargz/02-kourier.sh

    - name: Setup domain and autoscaler
      run: |
          INGRESS_HOST="127.0.0.1"
          KNATIVE_DOMAIN=$INGRESS_HOST.sslip.io
          kubectl patch configmap -n knative-serving config-domain -p "{\"data\": {\"$KNATIVE_DOMAIN\": \"\"}}"
          kubectl patch configmap -n knative-serving config-autoscaler -p "{\"data\": {\"allow-zero-initial-scale\": \"true\"}}"


    - name: Setup stock-only node
      run: ./scripts/cloudlab/setup_node.sh stock-only use-stargz

    - name: Check containerd service is running
      run: sudo screen -list | grep "containerd"

    - name: Check stargz-snapshotter is running
      run: sudo systemctl is-active --quiet stargz-snapshotter
    
    - name: Setup single-node cluster
      run: ./scripts/cluster/create_one_node_cluster.sh stock-only

    - name: Run test container with kn
      run: kn service apply stargz-test -f ./configs/knative_workloads/stargz-node.yaml --concurrency-target 1 

    - name: Curl container
      run: curl http://stargz-test.default.192.168.1.240.sslip.io | grep "Hello World"